#!/bin/bash

# Check if PYFILE environment variable is set
if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable is not set."
    exit 1
fi


PYFILEC="${PYFILE%.py}.pyc"
python3 -m py_compile "$PYFILE"
mv "__pycache__/$PYFILEC" .
rmdir "__pycache__"
echo "Compiling $PYFILE ..."
